# Generated by Django 4.1.6 on 2023-02-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'images'), ('VIDEO', 'videos')], max_length=5)),
                ('media', models.BinaryField()),
                ('labelling_data', models.JSONField(default=dict)),
                ('filename', models.CharField(default='Default', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Media',
                'verbose_name_plural': 'Web Media',
                'db_table': 'web_media',
            },
        ),
    ]
