# Generated by Django 4.1.6 on 2023-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmedia',
            name='media',
            field=models.BinaryField(max_length=1048576),
        ),
    ]
